language: erlang
otp_release:
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
notifications:
  webhooks:
    - https://wooga.slack.com/services/hooks/travis?token=mZNldRc90aXkhWxx71FKPuPN
